<project name="ant-tar-patched" default="jar">
	<!-- Properties -->
	<property name="jar.file" value="ant-tar-patched.jar" />
	<property name="src.java.dir" location="src/java" />
	<property name="build.dir" location="build" />
	<property name="build.classes.dir" location="${build.dir}/classes" />

	<path id="all.java.path">
		<pathelement location="${src.java.dir}" />
	</path>

	<!-- Targets -->
	<target name="build-init">
		<mkdir dir="${build.classes.dir}" />
	</target>

	<target name="compile" depends="build-init" description="Compiles the source code">
		<javac destdir="${build.classes.dir}" debug="true">
			<src refid="all.java.path" />
		</javac>
	</target>

	<target name="jar" depends="compile" description="Creates the jar file">
		<jar destfile="${build.dir}/${jar.file}" basedir="${build.classes.dir}" />
	</target>

	<target name="clean" description="Removes build files and undeploys extension">
		<delete dir="${build.dir}" />
	</target>

	<target name="sonar-scan" depends="compile" unless="skipSonarScan" description="Run SonarQube analysis">

		<property environment="env"/>
		<pathconvert property="sonar.java.libraries" refid="all.java.path" pathsep=","/>

		<fail message="SONAR_HOST_URL environment variable not set" unless="env.SONAR_HOST_URL"/>
		<fail message="SONAR_TOKEN environment variable not set" unless="env.SONAR_TOKEN"/>

		<echo message="Running SonarQube scan for ${ant.project.name}"/>

		<exec executable="sonar-scanner" failonerror="true">
			<arg value="-Dsonar.projectKey=${ant.project.name}"/>
			<arg value="-Dsonar.projectName=${ant.project.name}"/>
			<arg value="-Dsonar.projectBaseDir=${basedir}"/>
			<arg value="-Dsonar.java.source=1.8"/>
			<arg value="-Dsonar.sources=${basedir}"/>
			<arg value="-Dsonar.java.binaries=${build.classes.dir}"/>
			<arg value="-Dsonar.java.libraries=${sonar.java.libraries}"/>
			<arg value="-Dsonar.host.url=${env.SONAR_HOST_URL}"/>
			<arg value="-Dsonar.token=${env.SONAR_TOKEN}"/>
		</exec>
	</target>
	
</project>
